babies.df = read.table('/Users/hithyshikrishnamurthy/Documents/exam papers/ST2053/babies.txt',header = T)
attach(babies.df)
plot(Age, Birthwt, type = 'n', main = 'Seperate regression lines for male and female babies',xlab = 'geostational age',ylab = 'Birthweight (g)')
text(Age,Birthwt,c('F','M')[Gender])
legend(36,3400,pch = 'FM',merge = FALSE, lty = c(1,2),legend = c('Female','Male'))
female.babies.lm = lm(Birthwt ~ Age, data = babies.df, subset = Gender == 'Female')
summary(female.babies.lm)
male.babies.lm = lm(Birthwt ~ Age, data = babies.df, subset = Gender == 'Male')
summary(male.babies.lm)
abline(female.babies.lm,lty=1)
abline(male.babies.lm, lty = 2)
babies1.lm = lm(Birthwt ~ Age, data = babies.df)
plot(Age, Birthwt, type = 'n', main = 'Seperate regression lines for male and female babies',xlab = 'geostational age',ylab = 'Birthweight (g)')
text(Age,Birthwt,c('F','M')[Gender])
legend(36,3400,pch = 'FM',merge = FALSE, lty = c(1,2),legend = c('Female','Male'))
abline(babies1.lm,lty=1)
class(Gender)
levels(Gender)
options(constrasts = c(factor = 'contr.treatment', ordered = 'contr.poly'))
babies2.lm = update(babies1.lm, .~. + Gender)
model.matrix(babies2.lm)
coef(babies2.lm)
babies3.lm = update(babies2.lm, .~. + Age:Gender)
model.matrix(babies3.lm)
coef(babies3.lm)
